apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

nameSuffix: -sgx-mode-hw

images:
- name: quay.io/confidential-containers/reqs-payload
  newTag: e92cb67ea8956128a31950a0c3fa79a086dbaf1a
