name: gofmt
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  gofmt:
    name: gofmt
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: gofmt
        run : |
          gofmt -s -w .
          git diff --exit-code
