name: gofmt
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  gofmt:
    name: gofmt
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version-file: go.mod
          check-latest: true
      - name: gofmt
        run : |
          gofmt -s -w .
          git diff --exit-code
